# Generated by Django 5.1.6 on 2025-02-27 09:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('WALLET_UUID', models.IntegerField(db_index=True, primary_key=True, serialize=False, verbose_name='UUID кошелька')),
                ('user_name', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+\\Z')], verbose_name='Логин')),
                ('amount', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1, message='Минимальный размер 1!')], verbose_name='Баланс')),
            ],
        ),
    ]
