# Generated by Django 5.1.6 on 2025-03-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_wallet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwallet',
            name='WALLET_UUID',
        ),
        migrations.AddField(
            model_name='userwallet',
            name='wallet_uuid',
            field=models.UUIDField(db_index=True, default=122, primary_key=True, serialize=False, verbose_name='UUID кошелька'),
            preserve_default=False,
        ),
    ]
